# Generated by Django 2.2.8 on 2020-03-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200306_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='date_posted',
        ),
    ]
